CREATE DATABASE customer_behavior;
USE customer_behavior;
SELECT * FROM customer;
DESCRIBE customer;
SHOW COLUMNS FROM customer;
SELECT * FROM customer LIMIT 5;


-- Q1: What is the total revenue generated by male vs female customers?
SELECT gender,
       SUM(`purchase_amount_(usd)`) AS total_revenue
FROM customer
GROUP BY gender;

-- Q2. Customers who used discount but spent more than average
SELECT customer_id, `purchase_amount_(usd)`
FROM customer
WHERE discount_applied = 'Yes'
AND `purchase_amount_(usd)` > (
    SELECT AVG(`purchase_amount_(usd)`)
    FROM customer);

-- Q3. Top 5 products with highest average review rating
select item_purchased,avg(review_rating)as "Avarage Product Rating"
from customer
group by item_purchased
order by avg(review_rating)desc
limit 5;

-- Q4. Compare average purchase amount between standard and exprees shipping
select shipping_type,
avg(`purchase_amount_(usd)`) as avg_purchase
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

-- Q5. Do subscribed customers spend more?Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       AVG(`purchase_amount_(usd)`) AS avg_spend,
       SUM(`purchase_amount_(usd)`) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue DESC, avg_spend DESC;

-- Q6.Which 5 products with the highest percentage of discounted purchases
SELECT item_purchased,
       COUNT(CASE WHEN discount_applied = 'Yes' THEN 1 END) * 100.0 / COUNT(*) AS discount_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total no of previous purchase,
-- and show the count of each segment.
SELECT
CASE
    WHEN previous_purchases = 0 THEN 'New'
    WHEN previous_purchases BETWEEN 1 AND 5 THEN 'Returning'
    ELSE 'Loyal'
END AS customer_segment,
COUNT(*) AS total_customers
FROM customer
GROUP BY customer_segment;

-- Q8. Top 3 most purchased products within each category
SELECT category, item_purchased, purchase_count
FROM (
    SELECT category,
           item_purchased,
           COUNT(*) AS purchase_count,
           RANK() OVER(PARTITION BY category ORDER BY COUNT(*) DESC) AS rnk
    FROM customer
    GROUP BY category, item_purchased
) ranked_products
WHERE rnk <= 3;

-- Q9 Are customer who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(*) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q10 What are Revenue contribution of each age group?
SELECT age_group,
SUM(`purchase_amount_(usd)`) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;
